service: ISEI-Schedule-backend

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http: GET /api/v1/metainfo
      - http: GET /api/v1/schedule
